"""add phone number feild 


Revision ID: 6f9e680d63fb
Revises: 4a64c96a6262
Create Date: 2023-01-30 16:18:56.003527

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f9e680d63fb'
down_revision = '4a64c96a6262'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('_phone_number', sa.String(length=150), nullable=True))
    op.drop_column('user', 'first_name')
    op.drop_column('user', 'last_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('last_name', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('first_name', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.drop_column('user', '_phone_number')
    # ### end Alembic commands ###
