"""last test

Revision ID: 64a52eae631a
Revises: 8ef9106e8642
Create Date: 2023-01-31 17:03:18.978561

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64a52eae631a'
down_revision = '8ef9106e8642'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dispatch', sa.Column('message_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'dispatch', 'message', ['message_id'], ['id'])
    op.add_column('user', sa.Column('message_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'message', ['message_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'message_id')
    op.drop_constraint(None, 'dispatch', type_='foreignkey')
    op.drop_column('dispatch', 'message_id')
    # ### end Alembic commands ###
