"""phone_number setter

Revision ID: 5032cfc60bc4
Revises: c541e0d36800
Create Date: 2023-02-02 16:53:23.989593

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5032cfc60bc4'
down_revision = 'c541e0d36800'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
