"""change filed relationship

Revision ID: 8ef9106e8642
Revises: 8b094d112c72
Create Date: 2023-01-31 16:59:15.640628

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ef9106e8642'
down_revision = '8b094d112c72'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('dispatch_message_id_fkey', 'dispatch', type_='foreignkey')
    op.drop_column('dispatch', 'message_id')
    op.drop_constraint('user_message_id_fkey', 'user', type_='foreignkey')
    op.drop_column('user', 'message_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('message_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('user_message_id_fkey', 'user', 'message', ['message_id'], ['id'])
    op.add_column('dispatch', sa.Column('message_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('dispatch_message_id_fkey', 'dispatch', 'message', ['message_id'], ['id'])
    # ### end Alembic commands ###
