"""change relationsh

Revision ID: 8b094d112c72
Revises: 5fb60021a93e
Create Date: 2023-01-31 16:37:42.830259

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b094d112c72'
down_revision = '5fb60021a93e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
