"""alembic last_testtststst

Revision ID: 2eae486460f7
Revises: 64a52eae631a
Create Date: 2023-01-31 17:11:19.015077

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2eae486460f7'
down_revision = '64a52eae631a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
