"""add generate relatioinship 

Revision ID: fbc1734cdb88
Revises: 6f9e680d63fb
Create Date: 2023-01-30 17:15:48.535711

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbc1734cdb88'
down_revision = '6f9e680d63fb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
