"""change filed message on message_ref

Revision ID: c541e0d36800
Revises: 2eae486460f7
Create Date: 2023-01-31 17:34:55.964592

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c541e0d36800'
down_revision = '2eae486460f7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dispatch', sa.Column('message', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dispatch', 'message')
    # ### end Alembic commands ###
